from setuptools import setup
from pathlib import Path

this_directory = Path(__file__).parent

setup(
    name='metadynminer',
    version='0.8.3',
    description="Python package for efficient analysis of HILLS files generated by Plumed metadynamics simulations. ",
    long_description=(this_directory / "README.md").read_text(),
    long_description_content_type='text/markdown',
    url='https://github.com/Jan8be/metadynminer.py',
    author='Jan Beránek',
    author_email='Jan1.Beranek@vscht.cz',
    license='GPL-3.0',
    packages=['metadynminer'],
    python_requires='>=3.9',
    install_requires=['numpy>=2.1.1',
                      'matplotlib>=3.9.2',
                      'pandas>=2.2.2',
                      'vtk>=9.3.0',
                      'pyvista>=0.44.1',
                      'imageio>=2.35.1'
                      ],

    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',  
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3',
        'Topic :: Scientific/Engineering :: Bio-Informatics'
    ],
)
