name: Build

on: [ push, pull_request ]

env:
  CORE_CHANGED: false
  APP_CHANGED: false

jobs:
  install-metadynminer:
    name: ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
        exclude:
          - os: macos-latest
            python-version: "3.7"

    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for Ubuntu
        if: ${{ startsWith( matrix.os , 'ubuntu') }}
        run: |
          python --version
          python3 -m pip install --upgrade pip
          conda install numpy pytest pytest-cov matplotlib
          pip install -e .

      - name: Install dependencies for MacOS
        if: ${{ startsWith( matrix.os , 'macos') }}
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          pip3 install pytest pytest-cov
          conda install numpy matplotlib
          pip3 install -e .

      - name: Run tests
        run: |
          echo -e "Running tests"
          pytest tests/*.py
