name: docker

on: 
  workflow_dispatch:
    branches: [ 'main','hub' ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository_owner }}/${{ github.repository }}:latest
