#! vim: ts=2 expandtab:

name: docker

on: [ workflow_dispatch, pull_request, push ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: ghcr.io login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Repo lowercase
        id: lc
        run: |
          repo="${{ github.repository }}"
          echo "::set-output name=repo::${repo,,}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ steps.lc.outputs.repo }}:latest
